---
title: "Collaborative Filtering"
author: "Supanut Wanchai"
date: "2023-04-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## import library

```{r message=FALSE, include=FALSE}
set.seed(1234)
library("recommenderlab")
#library("tidyverse")
library("ggplot2")
library("tidyr")
library("dplyr")
data <- read.csv("Training_set.csv")
ans <- read.csv("Answers.csv")
```

# ratingmatrix
```{r}
m <- as.matrix(data)
m2 <- as.matrix(ans)
dimnames(m) <- list(user=paste("u", 1:50, sep=''),item=paste("i", 1:15, sep=''))
dimnames(m2) <- list(user=paste("u", 1:50, sep=''),item=paste("i", 1:15, sep=''))
r_r <- as(m, "realRatingMatrix")
r_ans <- as(m2, "realRatingMatrix")
#getRatingMatrix(r_r)
```

# Normalization Data
```{r}
r_m <- normalize(r_r)
#getRatingMatrix(r_m)
```

# split data without Normalization
```{r}
e <- evaluationScheme(r_r, method="split", train=0.9, goodRating=4, given=4)
e
train <- getData(e, "train")
known <- getData(e, "known")
unknown <- getData(e, "unknown")

# User-Based Collaborative Filtering 
r1 <- Recommender(train, method = "UBCF", param=list(nn=15))
p1 <- predict(r1, known, type="ratings")
p1

# Item-Based
r2 <- Recommender(train, method = "IBCF")
p2 <- predict(r2, known, type="ratings")
```

## Evaluating

```{r}
error <- rbind(
  UBCF = calcPredictionAccuracy(p1, getData(e, "unknown")),
  IBCF = calcPredictionAccuracy(p2, getData(e, "unknown")))
error
```

```{r}
df <- data.frame(matrix(ncol = 3, nrow = 1))
colnames(df) <- c('RMSE', 'MSE', 'MAE')

for (i in 1:20){
  r1 <- Recommender(train, method = "UBCF", param=list(nn=i))
  p1 <- predict(r1, known, type="ratings",n=5)
  UBCF = calcPredictionAccuracy(p1, getData(e, "unknown"))
  df = rbind(df,UBCF)
}

#as(p1,"list")

eva = df[-1,]
plot(x=1:20,y=eva$RMSE, ylim = c(min(eva)-0.1,max(eva)+0.1), type = "b", xlab = "nn", ylab = "Evaluate", col = "red")

# Add a second line
lines(x=1:20,y=eva$MSE, col = "blue", type = "b", lty = 2)
lines(x=1:20,y=eva$MAE, col = "green", type = "b", lty = 3)

# Add a legend to the plot
legend("topright", legend=c("RMSE", "MSE","MAE"), col=c("red", "blue","green"), lty = 1:3)
```

```{r eval=FALSE, include=FALSE}
scheme <- evaluationScheme(r_r, method = "cross-validation", k = 10, given = 4, goodRating = 4)
scheme
```

```{r eval=FALSE, include=FALSE}
algorithms <- list(`user-based CF` = list(name = "UBCF", param = list(nn = 3)), `item-based CF` = list(name = "IBCF", param = list(k = 100)))

results <- evaluate(scheme, algorithms, type = "topNList", n = c(1, 3, 5, 10), progress = FALSE)

plot(results, annotate = 2, legend = "topleft")

```

```{r}
r1 <- Recommender(train, method = "UBCF", param=list(nn=4))
p1 <- predict(r1, known, type="ratings",n=5)
real <- as.matrix(getRatingMatrix(r_ans)[unlist(getRatingMatrix(p1)@Dimnames[1]),])
full_predict = as.matrix(getRatingMatrix(known)+getRatingMatrix(p1))
RMSE(real,full_predict)
```

```{r}
#getRatingMatrix(r_r)[unlist(getRatingMatrix(p1)@Dimnames[1]),]
#getRatingMatrix(getData(e, "unknown"))
#getRatingMatrix(getData(e, "known"))
getModel(r1)
```

# Train all

```{r}
#test for nn
df <- data.frame(matrix(ncol = 3, nrow = 1))
colnames(df) <- c('RMSE', 'MSE', 'MAE')
real <- as.matrix(getRatingMatrix(r_ans))

for (i in 1:20){
  #recommender
  r1 <- Recommender(r_r, method = "UBCF", param=list(nn=i))
  p1 <- predict(r1, r_r, type="ratings",n=5)
  full_predict <- as.matrix(getRatingMatrix(r_r)+getRatingMatrix(p1))
  
  #evaluate
  rmse = RMSE(real,full_predict)
  mse = MSE(real,full_predict)
  mae = MAE(real,full_predict)
  df = rbind(df,c(rmse,mse,mae))
}

eva = df[-1,]
plot(x=1:20,y=eva$RMSE, ylim = c(min(eva)-0.1,max(eva)+0.1), type = "b", xlab = "nn", ylab = "Evaluate", col = "red")

# Add a second line
lines(x=1:20,y=eva$MSE, col = "blue", type = "b", lty = 2)
lines(x=1:20,y=eva$MAE, col = "green", type = "b", lty = 3)

# Add a legend to the plot
legend("topright", legend=c("RMSE", "MSE","MAE"), col=c("red", "blue","green"), lty = 1:3)
```

```{r}
#best nn
bnn = which.min(eva$RMSE)
r1 <- Recommender(r_r, method = "UBCF", param=list(nn=bnn))
p1 <- predict(r1, r_r, type="ratings",n=5)

real <- as.matrix(getRatingMatrix(r_ans)[unlist(getRatingMatrix(p1)@Dimnames[1]),])
full_predict = as.matrix(getRatingMatrix(r_r)+getRatingMatrix(p1))
RMSE(real,full_predict)
```

## Rounded
```{r}
ceil = ceiling(full_predict)
floor = floor(full_predict)
round = round(full_predict)
paste0("RMSE of full_predict: ",RMSE(real,full_predict))
paste0("RMSE of ceiling_predict: ",RMSE(real,ceil))
paste0("RMSE of floor_predict: ",RMSE(real,floor))
paste0("RMSE of round_predict: ",RMSE(real,round))
```
```{r}
#test for nn
df <- data.frame(matrix(ncol = 5, nrow = 1))

distance = c("Euclidean","Cosine","Pearson")


colnames(df) <- c('nn','is_norm','distance','type','RMSE')

real <- as.matrix(getRatingMatrix(r_ans))

for (i in 1:30){
  #recommender
  for (j in distance){
    for (k in 1:2){
      if(k==1){
        r1 <- Recommender(r_r, method = "UBCF", param=list(nn=i,method=j,normalize=NULL))
      }else{
        r1 <- Recommender(r_r, method = "UBCF", param=list(nn=i,method=j))
      }
      
      p1 <- predict(r1, r_r, type="ratings")
      
      #rounded
      full_predict <- as.matrix(getRatingMatrix(r_r)+getRatingMatrix(p1))
      ceil = ceiling(full_predict)
      floor = floor(full_predict)
      round = round(full_predict)
      
      #rmse
      full_rmse = RMSE(real,full_predict)
      c_rmse = RMSE(real,ceil)
      f_rmse = RMSE(real,floor)
      r_rmse = RMSE(real,round)
      
      df = rbind(df,c(i,k,j,"full",full_rmse))
      df = rbind(df,c(i,k,j,"ceiling",c_rmse))
      df = rbind(df,c(i,k,j,"floor",f_rmse))
      df = rbind(df,c(i,k,j,"round",r_rmse))
    }
  }
  
  #evaluate
  #mse = MSE(real,full_predict)
  #mae = MAE(real,full_predict)
}

eva = df[-1,] %>% mutate(is_norm = ifelse(is_norm==1,TRUE,FALSE),
                         nn=as.numeric(nn),
                         RMSE = as.numeric(RMSE),
                         condition = paste0(is_norm,"-",distance,"-",type))
```

```{r}
r1 <- Recommender(r_r, method = "UBCF", param=list(nn=20))
p1 <- predict(r1, r_r, type="ratings")
full_predict <- as.matrix(getRatingMatrix(r_r)+getRatingMatrix(p1))
```

```{r}
eva %>% ggplot(mapping = aes(x=nn,y=RMSE,group=interaction(is_norm,distance,type))) +
  geom_line(aes(col=type,linetype=is_norm)) +
  geom_point(aes(col=type, shape=distance))
```

```{r}
eva %>% filter(nn==10) %>% arrange(RMSE)
```
# test with Feedback.csv
```{r}
feedback <- read.csv("Feedback.csv")
m <- as.matrix(feedback[,-1])
dimnames(m) <- list(user=paste("u", 1:41, sep=''),item=paste("i", 1:15, sep=''))
r_r <- as(m, "realRatingMatrix")
```

## train data with Normalization
```{r}
# User-Based Collaborative Filtering 
r1 <- Recommender(r_r, method = "UBCF", param=list(nn=10))
p1 <- predict(r1, r_r, type="ratings")
full_predict <- as.matrix(getRatingMatrix(r_r)+getRatingMatrix(p1))

full_mean <- as.data.frame(lapply(feedback[,-1],as.double)) %>% mutate(across(where(is.numeric), ~replace_na(., mean(., na.rm=TRUE))))

#calcPredictionAccuracy(p1, getData(e, "unknown"))
```

```{r}
eva %>% filter(condition=="TRUE-Cosine-full") %>% arrange(RMSE)
```

```{r}
eva %>% filter(condition=="TRUE-Pearson-full") %>% arrange(RMSE)
```
```{r}
eva %>% filter(condition=="TRUE-Euclidean-full") %>% arrange(RMSE)
```


```{r}
write.csv(full_predict,file='user-based_prediction.csv', row.names=FALSE)
```
