---
title: "Stat480 proj"
author: "Supanut Wanchai"
date: "2023-11-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

## Data
```{r}
#import data
setwd('D:/2023_Fall/Stat_480/Project')
d <- read.csv("state_IL_lei_project.csv", header=TRUE)
library(readxl)
county <- read_excel("metro_area.xlsx")
bank_name <- read_excel("LEI_mapping.xlsx")
```

```{r}
#clean data
library(tidyverse)
data <- d
data <- select(data, -c('activity_year','derived_msa.md','state_code','census_tract','rate_spread','total_units','applicant_ethnicity.1','applicant_ethnicity.2','applicant_ethnicity.3','applicant_ethnicity.4','applicant_ethnicity.5','co.applicant_ethnicity.1','co.applicant_ethnicity.2','co.applicant_ethnicity.3','co.applicant_ethnicity.4','co.applicant_ethnicity.5','applicant_ethnicity_observed','co.applicant_ethnicity_observed','applicant_race.1','applicant_race.2','applicant_race.3','applicant_race.4','applicant_race.5','co.applicant_race.1','co.applicant_race.2','co.applicant_race.3','co.applicant_race.4','co.applicant_race.5','applicant_race_observed','co.applicant_race_observed','applicant_sex','co.applicant_sex','applicant_sex_observed','co.applicant_sex_observed','applicant_age','co.applicant_age','applicant_age_above_62','co.applicant_age_above_62','submission_of_application','aus.1','aus.2','aus.3','aus.4','aus.5','denial_reason.1','denial_reason.2','denial_reason.3','denial_reason.4','tract_population','tract_minority_population_percent','ffiec_msa_md_median_family_income','tract_to_msa_income_percentage','tract_owner_occupied_units','tract_one_to_four_family_homes','tract_median_age_of_housing_units'))

data <- select(data, -c('purchaser_type','preapproval','interest_rate','total_loan_costs','total_points_and_fees','origination_charges','discount_points','lender_credits'))
county <- county %>% mutate(county_code = str_sub(county_code,start=-5))

data$county_code <- as.character(data$county_code)
data <- data %>% left_join(county)
data <- data %>% left_join(bank_name)
data <- select(data, -c('derived_loan_product_type','derived_dwelling_category', 'state','metro_are','county','5_county'))

data <- data %>% filter(action_taken != 4)

data <- data %>% mutate(approve_flag = ifelse(action_taken %in% c(3,7), 0, 1 ))
data <- select(data, -c('county_code','action_taken','prepayment_penalty_term','intro_rate_period','multifamily_affordable_units','lei'))

data$metro[is.na(data$metro)] <- "non_metro"
#colSums(is.na(data))

data$income[is.na(data$income)] <- mean(data$income, na.rm =TRUE)
data$property_value <- as.numeric(data$property_value)
data$property_value[is.na(data$property_value)] <- mean(data$property_value, na.rm =TRUE)
data$loan_term[is.na(data$loan_term)] <- mode(data$loan_term)
#colSums(is.na(data))
data <- select(data, -c('conforming_loan_limit','debt_to_income_ratio','loan_to_value_ratio'))
data <- select(data, -c('loan_term'))

data$loan_type <- as.factor(data$loan_type)
data$loan_purpose <- as.factor(data$loan_purpose)
data$lien_status <- as.factor(data$lien_status)
data$reverse_mortgage <- as.factor(data$reverse_mortgage)
data$open.end_line_of_credit <- as.factor(data$open.end_line_of_credit)
data$business_or_commercial_purpose <- as.factor(data$business_or_commercial_purpose)
data$hoepa_status <- as.factor(data$hoepa_status)
data$negative_amortization <- as.factor(data$negative_amortization)
data$interest_only_payment <- as.factor(data$interest_only_payment)
data$balloon_payment <- as.factor(data$balloon_payment)
data$other_nonamortizing_features <- as.factor(data$other_nonamortizing_features)
data$construction_method <- as.factor(data$construction_method)
data$occupancy_type <- as.factor(data$occupancy_type)
data$manufactured_home_secured_property_type <- as.factor(data$manufactured_home_secured_property_type)
data$manufactured_home_land_property_interest <- as.factor(data$manufactured_home_land_property_interest)
data$applicant_credit_score_type <- as.factor(data$applicant_credit_score_type)
data$initially_payable_to_institution <- as.factor(data$initially_payable_to_institution)
data$co.applicant_credit_score_type <- as.factor(data$co.applicant_credit_score_type)

data <- select(data, -c('hoepa_status','initially_payable_to_institution'))

data <- data %>% mutate(derived_ethnicity = ifelse(derived_ethnicity %in% c("Ethnicity Not Available", "Free Form Text Only"), NA, derived_ethnicity),
                        derived_race = ifelse(derived_race %in% c("Race Not Available", "Free Form Text Only"), NA, derived_race),
                        derived_sex = ifelse(derived_sex %in% c("Sex Not Available", "Free Form Text Only"), NA, derived_sex)
                        )

data <- drop_na(data)
```

Dummy Variables
```{r}
library(fastDummies)
dummy <- dummy_cols(data[,1:23], select_columns = c("derived_ethnicity","derived_race","derived_sex","loan_type","loan_purpose","lien_status","reverse_mortgage","open.end_line_of_credit","business_or_commercial_purpose","negative_amortization","interest_only_payment","balloon_payment","other_nonamortizing_features","construction_method","occupancy_type","manufactured_home_secured_property_type","manufactured_home_land_property_interest","applicant_credit_score_type","co.applicant_credit_score_type","metro"), remove_selected_columns = TRUE)
```


Dimension Reduction
```{r}
library(gamlr)
y=data[,25]
lasso<- gamlr(dummy, y, lambda.min.ratio=1e-3, family = "binomial")
```

```{r}
coef(lasso)
```


remove c("reverse_mortgage", "negative_amortization","construction_method")

# clustering
```{r}
c_data = select(data, -c("reverse_mortgage", "negative_amortization","construction_method"))
c_data <- c_data[c_data$approve_flag == 1,]
```

```{r}
c_dummy <- dummy_cols(c_data[bank_name == "Bank of America",1:20], select_columns = c("derived_ethnicity","derived_race","derived_sex","loan_type","loan_purpose","lien_status","open.end_line_of_credit","business_or_commercial_purpose","interest_only_payment","balloon_payment","other_nonamortizing_features","occupancy_type","manufactured_home_secured_property_type","manufactured_home_land_property_interest","applicant_credit_score_type","co.applicant_credit_score_type","metro"), remove_selected_columns = TRUE)
```

```{r}
two <- kmeans(c_dummy,3,nstart=10)

two$centers # big differences on all accounts
```


```{r}
t_data = select(data, -c("reverse_mortgage", "negative_amortization","construction_method"))
```

```{r}
library(rpart)
BoA <- as.data.frame(t_data[bank_name == "Bank of America",])
fitBoA <- rpart(approve_flag ~ ., data = BoA[,-c(21)], method = 'class')
library(rpart.plot)
rpart.plot(fitBoA, extra = 106, main = "Bank of America")
```


```{r}
well <- as.data.frame(t_data[bank_name == "Wells Fargo",])
BMO <- as.data.frame(t_data[bank_name == "BMO Harris",])
PNC <- as.data.frame(t_data[bank_name == "PNC",])
JPM <- as.data.frame(t_data[bank_name == "JPMorgan",])
fitwell <- rpart(approve_flag ~ ., data = well[,-c(21)], method = 'class')
rpart.plot(fitwell, extra = 106, main = "Wells Fargo", cex = 0.75)
```

```{r}
fitBMO <- rpart(approve_flag ~ ., data = BMO[,-c(21)], method = 'class')
rpart.plot(fitBMO, extra = 106, main = "BMO Harris", cex = 0.75)
```

```{r}
fitJPM <- rpart(approve_flag ~ ., data = JPM[,-c(21)], method = 'class')
rpart.plot(fitJPM, extra = 106, main = "JPMorgan Chase & Co", cex = 0.75)
```
```{r}
fitPNC <- rpart(approve_flag ~ ., data = PNC[,-c(21)], method = 'class')
rpart.plot(fitPNC, extra = 106, main = "PNC", cex = 0.75)
```

```{r}
fitBoA <- rpart(approve_flag ~ ., data = BoA[BoA$applicant_credit_score_type %in% c(8,11),-c(21)], method = 'class')
rpart.plot(fitBoA, extra = 106, main = "Bank of America (credit type 8,11)", cex = 0.75)
```

```{r}
fitwell <- rpart(approve_flag ~ ., data = well[well$applicant_credit_score_type %in% c(8,11),-c(21)], method = 'class')
rpart.plot(fitwell, extra = 106, main = "Wells Fargo (credit type 8,11)", cex = 0.75)

fitBMO <- rpart(approve_flag ~ ., data = BMO[BMO$applicant_credit_score_type %in% c(8,11),-c(21)], method = 'class')
rpart.plot(fitBMO, extra = 106, main = "BMO Harris (credit type 8,11)", cex = 0.75)

fitJPM <- rpart(approve_flag ~ ., data = JPM[JPM$applicant_credit_score_type %in% c(8,11),-c(21)], method = 'class')
rpart.plot(fitJPM, extra = 106, main = "JPMorgan Chase & Co (credit type 8,11)", cex = 0.75)

fitPNC <- rpart(approve_flag ~ ., data = PNC[PNC$applicant_credit_score_type %in% c(8,11),-c(21)], method = 'class')
rpart.plot(fitPNC, extra = 106, main = "PNC (credit type 8,11)", cex = 0.75)
```


```{r}
fitBoA <- rpart(approve_flag ~ ., data = BoA[!BoA$applicant_credit_score_type %in% c(8,11),-c(21)], method = 'class')
rpart.plot(fitBoA, extra = 106, main = "Bank of America (credit type not 8,11)", cex = 0.75)

fitwell <- rpart(approve_flag ~ ., data = well[!well$applicant_credit_score_type %in% c(8,11),-c(21)], method = 'class')
rpart.plot(fitwell, extra = 106, main = "Wells Fargo (credit type not 8,11)", cex = 0.75)

fitBMO <- rpart(approve_flag ~ ., data = BMO[!BMO$applicant_credit_score_type %in% c(8,11),-c(21)], method = 'class')
rpart.plot(fitBMO, extra = 106, main = "BMO (credit type not 8,11)", cex = 0.75)

fitJPM <- rpart(approve_flag ~ ., data = JPM[!JPM$applicant_credit_score_type %in% c(8,11),-c(21)], method = 'class')
rpart.plot(fitJPM, extra = 106, main = "JPMorgan Chase & Co (credit type not 8,11)", cex = 0.75)

fitPNC <- rpart(approve_flag ~ ., data = PNC[!PNC$applicant_credit_score_type %in% c(8,11),-c(21)], method = 'class')
rpart.plot(fitPNC, extra = 106, main = "PNC (credit type not 8,11)", cex = 0.75)

```

## clustering
```{r}
clus_data <- select(t_data,c("loan_amount","property_value","income","Bank","approve_flag"))
clus_data[,1] <- scale(clus_data[,1])
clus_data[,2] <- scale(clus_data[,2])
clus_data[,3] <- scale(clus_data[,3])
colnames(clus_data) <- c("loan_amount","property_value","income","Bank","approve_flag")
```

```{r}
clus_data$ltv <- clus_data$loan_amount/clus_data$property_value
```

```{r}
plot(clus_data[clus_data$Bank == "JPMorgan",2:3],xlim=c(0,2),ylim=c(0,5))
plot(clus_data[clus_data$Bank == "PNC",2:3],xlim=c(0,2),ylim=c(0,5))
plot(clus_data[clus_data$Bank == "BMO Harris",2:3],xlim=c(0,2),ylim=c(0,5))
```


```{r}
par(mfrow = c(2,2))
plot(clus_data[clus_data$Bank == "BMO Harris",c(3,6)],xlim=c(0,2))
plot(clus_data[clus_data$Bank == "PNC",c(3,6)],xlim=c(0,2))
plot(clus_data[clus_data$Bank == "JPMorgan",c(3,6)],xlim=c(0,2))
```

```{r}
filter(clus_data, Bank == "JPMorgan", ltv > 100) %>% arrange(desc(loan_amount))
```





```{r}
two <- kmeans(clus_data[,1:3],3,nstart=10)
two$centers # big differences on all accounts
```






## pca

```{r}
mypca <- prcomp(dummy)
plot(mypca)
```
```{r}
summary(mypca)
```

```{r}
mypca
```

PCA does not help.
